name: deploy

on:
  # すべてのブランチへの push をトリガーにする
  push:
    branches: ["*"]

  # Actions タブからの手動実行
  workflow_dispatch:

permissions:
  id-token: write
  pages: write

defaults:
  run:
    shell: bash

jobs:
  # すべてのブランチでビルドを走らせるジョブ
  build:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "latest"
          extended: true
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo --minify -D --baseURL "${{ steps.pages.outputs.base_url }}/"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  # ビルドが完了したら、mainブランチのときだけデプロイするジョブ
  deploy:
    needs: build
    runs-on: ubuntu-latest

    # main ブランチかどうかの判定
    if: github.ref == 'refs/heads/main'

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
