name: run-textlint-minimum
on:
  pull_request:
    types: [opened]
  push:
  workflow_dispatch:

jobs:
  run-textlint-minimum:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm install
      - run: npx textlint ./content/**/*.md ./content/*.md
