name: textlint
on:
  pull_request:
    types: [opened]
  push:
  workflow_dispatch:

jobs:
  textlint:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm install
      - run: npx textlint ./content/**/*.ja_jp.md ./content/*.ja_jp.md | tee ./.textlint.log
      - run: npx textlint ./content/**/*.ja_jp.md ./content/*.ja_jp.md
      - if: ${{ failure() }}
        run: gh pr comment --body-file ./.textlint.log "${URL}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: ${{ github.event.pull_request.html_url }}
